config/routes.rb
Rails.application.routes.draw do
  resources :induction_sessions
  devise_for :users
  resources :users
  root 'static_pages#index'

  get 'dashboard/index', as: 'dashboard'
  get 'static_pages/index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.admin?
      can :manage, :all
    else
      can :read, InductionSession
    end
  end
end

app/models/induction_session.rb
class InductionSession < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def full_name
    [first_name, last_name].join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/induction_sessions_controller.rb
class InductionSessionsController < ApplicationController
  before_action :set_induction_session, only: [:show, :edit, :update, :destroy]

  # GET /induction_sessions
  # GET /induction_sessions.json
  def index
    @induction_sessions = InductionSession.all
  end

  # GET /induction_sessions/1
  # GET /induction_sessions/1.json
  def show
  end

  # GET /induction_sessions/new
  def new
    @induction_session = InductionSession.new
  end

  # GET /induction_sessions/1/edit
  def edit
  end

  # POST /induction_sessions
  # POST /induction_sessions.json
  def create
    @induction_session = InductionSession.new(induction_session_params)

    respond_to do |format|
      if @induction_session.save
        format.html { redirect_to @induction_session, notice: 'Induction session was successfully created.' }
        format.json { render :show, status: :created, location: @induction_session }
      else
        format.html { render :new }
        format.json { render json: @induction_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /induction_sessions/1
  # PATCH/PUT /induction_sessions/1.json
  def update
    respond_to do |format|
      if @induction_session.update(induction_session_params)
        format.html { redirect_to @induction_session, notice: 'Induction session was successfully updated.' }
        format.json { render :show, status: :ok, location: @induction_session }
      else
        format.html { render :edit }
        format.json { render json: @induction_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /induction_sessions/1
  # DELETE /induction_sessions/1.json
  def destroy
    @induction_session.destroy
    respond_to do |format|
      format.html { redirect_to induction_sessions_url, notice: 'Induction session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_induction_session
      @induction_session = InductionSession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def induction_session_params
      params.require(:induction_session).permit(:user, :date)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_filter :authenticate_user!

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/induction_sessions_helper.rb
module InductionSessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/induction_sessions/_form.html.erb
<%= form_for(@induction_session) do |f| %>
  <% if @induction_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@induction_session.errors.count, "error") %> prohibited this induction_session from being saved:</h2>

      <ul>
      <% @induction_session.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/induction_sessions/edit.html.erb
<h1>Editing Induction Session</h1>

<%= render 'form' %>

<%= link_to 'Show', @induction_session %> |
<%= link_to 'Back', induction_sessions_path %>

app/views/induction_sessions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Induction Sessions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @induction_sessions.each do |induction_session| %>
      <tr>
        <td><%= induction_session.user %></td>
        <td><%= induction_session.date %></td>
        <td><%= link_to 'Show', induction_session %></td>
        <td><%= link_to 'Edit', edit_induction_session_path(induction_session) %></td>
        <td><%= link_to 'Destroy', induction_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Induction session', new_induction_session_path %>

app/views/induction_sessions/new.html.erb
<h1>New Induction Session</h1>

<%= render 'form' %>

<%= link_to 'Back', induction_sessions_path %>

app/views/induction_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @induction_session.user %>
</p>

<p>
  <strong>Date:</strong>
  <%= @induction_session.date %>
</p>

<%= link_to 'Edit', edit_induction_session_path(@induction_session) %> |
<%= link_to 'Back', induction_sessions_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
<div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
    </button>
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'logo.png' %>
    <% end %>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <!-- Left menu -->
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
        <% if can? :manage, User %>


          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Users</a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Users", users_path %></li>
              <li><%= link_to "New Users", new_user_path %></li>
            </ul>
          </li>


        <% end %>
      <% end %>
    </ul>

    <!-- Right menu -->
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to edit_user_registration_path do %>
              <%= fa_icon "cog" %> Edit My Profile
            <% end %>
          </li>
          <li role="separator" class="divider"></li>
          <li>
            <%= link_to destroy_user_session_path, :method => :delete do %>
              <%= fa_icon "sign-out" %> Log Out
            <% end %>
          </li>
        </ul>
      </li>
      <% else %>
        <li><a href="mailto:accounts@makespace.org">Having trouble? Contact Us</a></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MakespaceInduction</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
</body>
</html>

app/views/static_pages/index.html.erb
<div class="jumbotron">
  <h1>Join Makespace</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent varius dignissim justo. Phasellus at nibh tempor, faucibus purus a, lacinia leo. Phasellus ligula dui, efficitur quis tortor at, imperdiet ultricies tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis gravida pretium ante sed posuere.</p>
  <%= link_to "Register for an Induction", new_user_registration_path, class: 'btn btn-primary btn-lg' %>
  <%= link_to "Already a member? Log in", new_user_session_path, class: 'btn btn-primary btn-lg' %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

    <div class="field">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= user.email %>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>